### ISSUE TITLE
Error in UseMethod("label")

### ISSUE THREAD

**Issue by proshano** [BavoDC/CalibrationCurves#1]
Hi there,

Really appreciate your package.

There's an issue when using val.prob.ci.2 in R 3.6.1 that I haven't encountered in the past:

Error in UseMethod("label") : 
  no applicable method for 'label' applied to an object of class "c('double', 'numeric')"

Do you have any suggestions?

Thanks!
Pavel

**Comment by BavoDC** [comment]
Hi,

Great to hear and many thanks for letting me know about the issue you are experiencing!

Could you provide me with a minimal working example? I tried to reproduce the error by using the examples in the help file, but I do not seem to get the error message. That way I can try to figure out what went wrong.

Best regards,

Bavo.
