### ISSUE TITLE
valPRobggplot fails if options 'm', 'g', or 'cuts' are specified.

### ISSUE THREAD

**Issue by jwilliman** [BavoDC/CalibrationCurves#4]
Brilliant to find a ggplot version of the Calibration curve

**The problem**
`valPRobggplot` fails if options 'm', 'g', or 'cuts' are specified, giving the error message `object 'all.col' not found`. Searching the code for `all.col` returns only line 298 `all.col <- c(all.col, col.smooth)`. 
Removing this line appears to fix the problem without causing any other issues?

(As a stylistic issue, I find that the logistic calibration curve tends to get hidden behind the flexible calibration curve, especially if `CL.smooth = "fill"`. I wonder if the logistic calibration could be added after the flexible calibration curve). 

Thanks :)

**Example**
``` r
suppressPackageStartupMessages(library(CalibrationCurves))
set.seed(1783)

# Simulate training data
X      = replicate(4, rnorm(5e2))
p0true = binomial()$linkinv(cbind(1, X) %*% c(0.1, 0.5, 1.2, -0.75, 0.8))
y      = rbinom(5e2, 1, p0true)
Df     = data.frame(y, X)

# Fit logistic model
FitLog = lrm(y ~ ., Df)

# Simulate validation data
Xval   = replicate(4, rnorm(5e2))
p0true = binomial()$linkinv(cbind(1, Xval) %*% c(0.1, 0.5, 1.2, -0.75, 0.8))
yval   = rbinom(5e2, 1, p0true)
Pred   = binomial()$linkinv(cbind(1, Xval) %*% coef(FitLog))

# Default calibration plot
valProbggplot(Pred, yval, g = 5)
#> Error in valProbggplot(Pred, yval, g = 5): object 'all.col' not found
valProbggplot(Pred, yval, m = 5)
#> Error in valProbggplot(Pred, yval, m = 5): object 'all.col' not found
valProbggplot(Pred, yval, cuts = c(.2,.4,.6,.8))
#> Error in valProbggplot(Pred, yval, cuts = c(0.2, 0.4, 0.6, 0.8)): object 'all.col' not found
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by BavoDC** [comment]
Hi! Glad to hear that you like the ggplot version and many thanks for letting me know about the bug!

As you suspected, this is indeed due to the code on line 298 (remnant of the val.prob.ci.2 code when I rewrote the code to a ggplot version). I have removed it and now it works. I will push it to Github asap. 

I agree with the remark on the logistic calibration curve. I will add it to my to-do list. I am working on a big update of the package (added some functionalities and working on a vignette), so I will try to integrate it with the new version.

**Comment by jwilliman** [comment]
Brilliant. Thanks. 

I also noticed the `size` attribute didn't seem to have any effect on changing the text size of the `abc` calibration statistics. I think it needs to be added to the end of line 348-349, i.e.

`gg = gg + annotate("text", x = statloc[1], y = statloc[2], 
                           label = stats.2, hjust = 0, size = size)`

**Comment by BavoDC** [comment]
Thanks for noticing this (and for taking the time to write this down)! I have adjusted the code and pushed it to Github. If there is anything else, let me know. I try to test as exhaustively as possible, but unfortunately there are some bugs that go unnoticed. Thanks again for catching these bugs!
