### ISSUE TITLE
Do you have any tutorial or manual for this package? 

### ISSUE THREAD

**Issue by xiw588** [BavoDC/CalibrationCurves#5]

**Comment by BavoDC** [comment]
Hi, 
I am currently working on a major update of the package which will include a tutorial. I will release it as soon as I finish the accompanying paper. I hope to finish the update of the package within the coming month. I can provide you with a simple example for now if you can't afford to wait that long. 
Best,
Bavo.

**Comment by xiw588** [comment]
Thank you for your response! Yes, it will be super if you can send me a brief tutorial!

**Comment by BavoDC** [comment]
You can find a brief tutorial at [https://bavodc.github.io/websiteCalibrationCurves/](https://bavodc.github.io/websiteCalibrationCurves/). This will be more extensive in the future, but I hope it is sufficient for now.

**Comment by xiw588** [comment]
Thank you so much!! This is very helpful.

**Comment by BavoDC** [comment]
Glad to hear! If possible, try to cite the paper and the package.
